// <auto-generated />
using System;
using Api.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240814132105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Api.Persistance.Model.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Api.Persistance.Model.ClientWhitelisting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TenantId");

                    b.ToTable("ClientWhitelistings");
                });

            modelBuilder.Entity("Api.Persistance.Model.FinancialDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ClientVatVatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientVatVatNumber");

                    b.HasIndex("TenantId");

                    b.ToTable("FinancialDocuments");
                });

            modelBuilder.Entity("Api.Persistance.Model.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWhitelisted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Api.Persistance.Model.VatRegistration", b =>
                {
                    b.Property<long>("VatNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VatNumber");

                    b.HasIndex("ClientId");

                    b.ToTable("VatRegistrations");
                });

            modelBuilder.Entity("Api.Persistance.Model.ClientWhitelisting", b =>
                {
                    b.HasOne("Api.Persistance.Model.Client", "Client")
                        .WithMany("ClientWhitelisting")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Persistance.Model.Tenant", "Tenant")
                        .WithMany("ClientWhitelisting")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Api.Persistance.Model.FinancialDocument", b =>
                {
                    b.HasOne("Api.Persistance.Model.VatRegistration", "ClientVat")
                        .WithMany("FinancialDocuments")
                        .HasForeignKey("ClientVatVatNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Persistance.Model.Tenant", "Tenant")
                        .WithMany("FinancialDocuments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientVat");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Api.Persistance.Model.VatRegistration", b =>
                {
                    b.HasOne("Api.Persistance.Model.Client", "Client")
                        .WithMany("ClientVats")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Api.Persistance.Model.Client", b =>
                {
                    b.Navigation("ClientVats");

                    b.Navigation("ClientWhitelisting");
                });

            modelBuilder.Entity("Api.Persistance.Model.Tenant", b =>
                {
                    b.Navigation("ClientWhitelisting");

                    b.Navigation("FinancialDocuments");
                });

            modelBuilder.Entity("Api.Persistance.Model.VatRegistration", b =>
                {
                    b.Navigation("FinancialDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
